#This is the makefile used by the make utility to compile the SpecDecBot project
SPECDECBOT : main.cpp sql.hpp
	sudo g++ test.cpp -o ../bin/test -l sqlite3 -std=c++14
	sudo chmod +x ../bin/test
	sudo chmod 777 ../bin/test
	../bin/test

