#This is the makefile used by the make utility to compile the SpecDecBot project
SPECDECBOT : main.cpp
	sudo g++ main.cpp -o ../bin/main -std=c++14
	sudo chmod +x ../bin/main
	sudo chmod 777 ../bin/main
	../bin/main

